main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

# Node.js compatibility: https://developers.cloudflare.com/workers/runtime-apis/nodejs/
compatibility_date = "2024-09-23"
workers_dev = false
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[vars]
MAINTENANCE_MODE = "false"
MAINTENANCE_DATE = ""