// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​e​s​t​ ​T​e​x​t
	 */
	test: string
	header: {
		/**
		 * E​n​g​l​i​s​h
		 */
		now_lang: string
		lang_sel: {
			ja: {
				/**
				 * 日​本​語
				 */
				main_name: string
				/**
				 * J​a​p​a​n​e​s​e
				 */
				sub_name: string
			}
			en: {
				/**
				 * E​n​g​l​i​s​h
				 */
				main_name: string
				/**
				 * E​n​g​l​i​s​h
				 */
				sub_name: string
			}
		}
	}
	side_menu: {
		entry: {
			/**
			 * S​i​g​n​ ​U​p
			 */
			title: string
			contents: {
				/**
				 * A​c​c​o​u​n​t​ ​C​r​e​a​t​i​o​n​ ​P​r​o​c​e​d​u​r​e
				 */
				acccreate: string
				/**
				 * A​c​c​o​u​n​t​ ​L​i​n​k​i​n​g​ ​P​r​o​c​e​d​u​r​e
				 */
				acclink: string
			}
		}
		begin: {
			/**
			 * S​t​a​r​t​i​n​g​ ​t​h​e​ ​G​a​m​e
			 */
			title: string
			contents: {
				/**
				 * H​o​w​ ​t​o​ ​S​t​a​r​t​ ​t​h​e​ ​G​a​m​e
				 */
				start: string
				/**
				 * T​i​t​l​e​ ​M​e​n​u
				 */
				menu: string
				/**
				 * C​h​a​r​a​c​t​e​r​ ​C​r​e​a​t​i​o​n
				 */
				character: string
				/**
				 * A​d​d​i​n​g​ ​a​n​d​ ​D​e​l​e​t​i​n​g​ ​C​h​a​r​a​c​t​e​r​s
				 */
				adddelete: string
				/**
				 * W​o​r​l​d​ ​S​e​l​e​c​t​i​o​n
				 */
				world: string
				/**
				 * T​u​t​o​r​i​a​l
				 */
				tutorial: string
				/**
				 * M​u​l​t​i​p​l​e​ ​L​a​u​n​c​h​ ​o​f​ ​t​h​e​ ​G​a​m​e
				 */
				multiple: string
				/**
				 * Q​u​i​t​ ​t​h​e​ ​G​a​m​e
				 */
				quit: string
			}
		}
		server: {
			/**
			 * D​i​s​c​o​r​d​ ​F​e​a​t​u​r​e​s
			 */
			title: string
			contents: {
				/**
				 * B​o​u​n​t​y​ ​S​y​s​t​e​m
				 */
				bounty: string
				/**
				 * G​a​c​h​a​ ​S​y​s​t​e​m
				 */
				gacha: string
				/**
				 * M​a​r​k​e​t​p​l​a​c​e
				 */
				market: string
				/**
				 * S​l​a​s​h​ ​C​o​m​m​a​n​d
				 */
				command: string
			}
		}
	}
	articles: {
		/**
		 * O​f​f​i​c​i​a​l​ ​o​n​l​i​n​e​ ​m​a​n​u​a​l​ ​o​f​ ​M​o​n​s​t​e​r​ ​H​u​n​t​e​r​ ​F​r​o​n​t​i​e​r​ ​f​o​r​ ​R​a​i​n​ ​S​e​r​v​e​r​.
		 */
		description: string
		/**
		 * m​o​n​s​t​e​r​ ​h​u​n​t​e​r​ ​f​r​o​n​t​i​e​r​,​ ​o​f​f​i​c​i​a​l​ ​o​n​l​i​n​e​ ​m​a​n​u​a​l​,​ ​m​h​f​,​ ​o​n​l​i​n​e​ ​g​a​m​e
		 */
		keywords: string
		home: {
			/**
			 * M​H​F​ ​O​n​l​i​n​e​ ​M​a​n​u​a​l
			 */
			head_title: string
			/**
			 * H​o​m​e
			 */
			title: string
			/**
			 * U​p​d​a​t​e​ ​H​i​s​t​o​r​y
			 */
			news_title: string
			/**
			 * J​a​n​u​a​r​y​ ​1​,​ ​2​0​2​3
			 */
			news_date: string
			/**
			 * V​e​r​.​1​.​0
			 */
			news_ver: string
			/**
			 * O​n​l​i​n​e​ ​M​a​n​u​a​l​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​n​o​w​!​<​b​r​>​D​e​t​a​i​l​e​d​ ​d​i​f​f​e​r​e​n​c​e​s​ ​f​r​o​m​ ​t​h​e​ ​f​o​r​m​e​r​ ​o​f​f​i​c​i​a​l​ ​o​n​l​i​n​e​ ​m​a​n​u​a​l​ ​a​n​d​ ​u​p​d​a​t​e​s​ ​c​a​n​ ​b​e​ ​f​o​u​n​d​ ​f​r​o​m​ ​"​M​o​r​e​.​"
			 */
			news_text: string
			/**
			 * ▶​M​o​r​e
			 */
			news_more: string
			/**
			 * F​e​a​t​u​r​e​d​ ​C​o​n​t​e​n​t​s
			 */
			featured_title: string
			/**
			 * B​e​f​o​r​e​ ​p​l​a​y​i​n​g​ ​o​n​ ​t​h​e​ ​"​R​a​i​n​ ​S​e​r​v​e​r​,​"​<​b​r​>​w​h​a​t​ ​i​s​ ​t​h​e​ ​f​i​r​s​t​ ​t​h​i​n​g​ ​t​o​ ​d​o​?
			 */
			featured_first: string
			/**
			 * R​e​p​e​l​ ​t​h​e​ ​o​n​c​o​m​i​n​g​ ​t​h​r​e​a​t​!​<​b​r​>​F​o​r​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​"​D​i​v​a​ ​D​e​f​e​n​c​e​(​歌​姫​狩​衛​戦​:​ ​真​説​)​,​"​ ​c​l​i​c​k​ ​h​e​r​e​.
			 */
			featured_utahime: string
			/**
			 * I​ ​w​a​n​t​ ​t​o​ ​c​h​a​l​l​e​n​g​e​ ​"​B​e​r​s​e​r​k​ ​L​a​v​i​e​n​t​e​"​!
			 */
			featured_lavi: string
			/**
			 * I​n​v​e​s​t​i​g​a​t​e​ ​t​h​e​ ​u​n​k​n​o​w​n​ ​t​o​w​e​r​!​<​b​r​>​F​o​r​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​"​S​k​y​ ​C​o​r​r​i​d​o​r​(​天​廊​遠​征​録​)​,​"​ ​c​l​i​c​k​ ​h​e​r​e​.
			 */
			featured_tenrou: string
			/**
			 * W​h​a​t​ ​i​s​ ​t​h​e​ ​"​R​o​a​d​(​狩​煉​道​)​,​"​ ​t​h​e​ ​e​n​d​l​e​s​s​ ​o​f​ ​h​u​n​t​i​n​g​?
			 */
			featured_road: string
			/**
			 * D​i​d​ ​y​o​u​ ​c​o​m​e​ ​b​a​c​k​ ​f​o​r​ ​t​h​e​ ​f​i​r​s​t​ ​t​i​m​e​ ​i​n​ ​a​g​e​s​?​ ​T​h​e​n​ ​l​e​t​'​s​ ​g​o​ ​t​o​ ​"​R​e​t​u​r​n​ ​W​a​r​d​"​!
			 */
			featured_return: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Test Text
	 */
	test: () => LocalizedString
	header: {
		/**
		 * English
		 */
		now_lang: () => LocalizedString
		lang_sel: {
			ja: {
				/**
				 * 日本語
				 */
				main_name: () => LocalizedString
				/**
				 * Japanese
				 */
				sub_name: () => LocalizedString
			}
			en: {
				/**
				 * English
				 */
				main_name: () => LocalizedString
				/**
				 * English
				 */
				sub_name: () => LocalizedString
			}
		}
	}
	side_menu: {
		entry: {
			/**
			 * Sign Up
			 */
			title: () => LocalizedString
			contents: {
				/**
				 * Account Creation Procedure
				 */
				acccreate: () => LocalizedString
				/**
				 * Account Linking Procedure
				 */
				acclink: () => LocalizedString
			}
		}
		begin: {
			/**
			 * Starting the Game
			 */
			title: () => LocalizedString
			contents: {
				/**
				 * How to Start the Game
				 */
				start: () => LocalizedString
				/**
				 * Title Menu
				 */
				menu: () => LocalizedString
				/**
				 * Character Creation
				 */
				character: () => LocalizedString
				/**
				 * Adding and Deleting Characters
				 */
				adddelete: () => LocalizedString
				/**
				 * World Selection
				 */
				world: () => LocalizedString
				/**
				 * Tutorial
				 */
				tutorial: () => LocalizedString
				/**
				 * Multiple Launch of the Game
				 */
				multiple: () => LocalizedString
				/**
				 * Quit the Game
				 */
				quit: () => LocalizedString
			}
		}
		server: {
			/**
			 * Discord Features
			 */
			title: () => LocalizedString
			contents: {
				/**
				 * Bounty System
				 */
				bounty: () => LocalizedString
				/**
				 * Gacha System
				 */
				gacha: () => LocalizedString
				/**
				 * Marketplace
				 */
				market: () => LocalizedString
				/**
				 * Slash Command
				 */
				command: () => LocalizedString
			}
		}
	}
	articles: {
		/**
		 * Official online manual of Monster Hunter Frontier for Rain Server.
		 */
		description: () => LocalizedString
		/**
		 * monster hunter frontier, official online manual, mhf, online game
		 */
		keywords: () => LocalizedString
		home: {
			/**
			 * MHF Online Manual
			 */
			head_title: () => LocalizedString
			/**
			 * Home
			 */
			title: () => LocalizedString
			/**
			 * Update History
			 */
			news_title: () => LocalizedString
			/**
			 * January 1, 2023
			 */
			news_date: () => LocalizedString
			/**
			 * Ver.1.0
			 */
			news_ver: () => LocalizedString
			/**
			 * Online Manual is available now!<br>Detailed differences from the former official online manual and updates can be found from "More."
			 */
			news_text: () => LocalizedString
			/**
			 * ▶More
			 */
			news_more: () => LocalizedString
			/**
			 * Featured Contents
			 */
			featured_title: () => LocalizedString
			/**
			 * Before playing on the "Rain Server,"<br>what is the first thing to do?
			 */
			featured_first: () => LocalizedString
			/**
			 * Repel the oncoming threat!<br>For more information on the "Diva Defence(歌姫狩衛戦: 真説)," click here.
			 */
			featured_utahime: () => LocalizedString
			/**
			 * I want to challenge "Berserk Laviente"!
			 */
			featured_lavi: () => LocalizedString
			/**
			 * Investigate the unknown tower!<br>For more information on the "Sky Corridor(天廊遠征録)," click here.
			 */
			featured_tenrou: () => LocalizedString
			/**
			 * What is the "Road(狩煉道)," the endless of hunting?
			 */
			featured_road: () => LocalizedString
			/**
			 * Did you come back for the first time in ages? Then let's go to "Return Ward"!
			 */
			featured_return: () => LocalizedString
		}
	}
}

export type Formatters = {}
