// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * t​e​s​t
	 */
	HI: string
	header: {
		/**
		 * E​n​g​l​i​s​h
		 */
		label: string
		lang_menu: {
			ja: {
				/**
				 * 日​本​語
				 */
				main_name: string
				/**
				 * J​a​p​a​n​e​s​e
				 */
				sub_name: string
			}
			en: {
				/**
				 * E​n​g​l​i​s​h
				 */
				main_name: string
				/**
				 * E​n​g​l​i​s​h
				 */
				sub_name: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * test
	 */
	HI: () => LocalizedString
	header: {
		/**
		 * English
		 */
		label: () => LocalizedString
		lang_menu: {
			ja: {
				/**
				 * 日本語
				 */
				main_name: () => LocalizedString
				/**
				 * Japanese
				 */
				sub_name: () => LocalizedString
			}
			en: {
				/**
				 * English
				 */
				main_name: () => LocalizedString
				/**
				 * English
				 */
				sub_name: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
