// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * t​e​s​t​ ​t​e​x​t​.
	 */
	testText: string
}

export type TranslationFunctions = {
	/**
	 * test text.
	 */
	testText: () => LocalizedString
}

export type Formatters = {}
